[package]
name = "git-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
base64 = "0.22.1"
env_logger = "0.11.8"
lazy_static = "1.5.0"
log = "0.4.27"

[[bin]]
name = "git-server"
path = "src/main.rs"
